name: uber-fares
channels:
  - conda-forge
  - domdfcoding
  - defaults
dependencies:
  - click
  - coverage
  - flakeheaven
  - folium
  - furo
  - geopandas
  - geopy
  - holidays
  - jupyter
  - mccabe
  - numpy
  - pandas
  - pylint
  - python=3.9
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - sphinx
  - sphinx-autobuild
  - sphinx-pyproject
  - sphinxcontrib-napoleon
  - yapf
