name: uber-fares
channels:
  - conda-forge
  - https://conda.anaconda.org/domdfcoding
  - defaults
dependencies:
  - click
  - coverage
  - flake8
  - folium
  - furo
  - geopandas
  - geopy
  - holidays
  - jupyter
  - numpy
  - pandas
  - python
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - sphinx
  - sphinx-autobuild
  - sphinx-pyproject
  - sphinxcontrib-napoleon
  - yapf
